name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - uses: actions/checkout@v2
    - name: Setup .NET 3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0.100'  
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./IoTHubClientGenerator
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./IoTHubClientGenerator
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./IoTHubClientGenerator
      
